<<<<<<< HEAD
# Generated by Django 5.2 on 2025-05-02 15:31

import ckeditor.fields
import django.contrib.auth.models
import django.contrib.auth.validators
=======
# Generated by Django 5.1 on 2025-04-08 05:29

import ckeditor.fields
import django.contrib.auth.models
>>>>>>> b32e3409f2d87f193ea8976c0fd0ca6edf64df33
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> b32e3409f2d87f193ea8976c0fd0ca6edf64df33
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('gallery_image', models.ImageField(upload_to='media/gallery/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=255)),
                ('slider_image', models.ImageField(blank=True, null=True, upload_to='media/slider/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> b32e3409f2d87f193ea8976c0fd0ca6edf64df33
            name='LJNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('sub_title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('author_id', models.EmailField(max_length=255)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=255)),
<<<<<<< HEAD
                ('visibility', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=255, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('ljnews_image', models.ImageField(blank=True, null=True, upload_to='media/ljnews/')),
                ('views', models.IntegerField(default=0)),
=======
                ('is_featured', models.BooleanField(default=False)),
                ('ljnews_image', models.ImageField(blank=True, null=True, upload_to='media/ljnews/')),
>>>>>>> b32e3409f2d87f193ea8976c0fd0ca6edf64df33
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.category')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('sub_title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('author_id', models.EmailField(editable=False, max_length=255)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('DRAFT', 'DRAFT')], max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('news_image', models.ImageField(upload_to='media/news/')),
<<<<<<< HEAD
                ('views', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.category')),
=======
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.category')),
                ('likes', models.ManyToManyField(blank=True, related_name='Post_likes', to=settings.AUTH_USER_MODEL)),
>>>>>>> b32e3409f2d87f193ea8976c0fd0ca6edf64df33
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('ljnews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.ljnews')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.news')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=10, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/profile/')),
                ('approved', models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('NOT APPROVED', 'NOT APPROVED')], max_length=255, null=True)),
                ('enrollment_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('Choose Role', 'Choose Role'), ('Student', 'Student'), ('Faculty/Staff', 'Faculty/Staff')], default='Choose Role', max_length=20)),
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.news')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('enrollment_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('role', models.CharField(choices=[('Choose Role', 'Choose Role'), ('Student', 'Student'), ('Faculty/Staff', 'Faculty/Staff')], default='Choose Role', max_length=20)),
                ('profile_image', models.ImageField(upload_to='media/profile/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('profile_image', models.ImageField(upload_to='media/profile/')),
                ('enrollment_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.CharField(choices=[('Choose Role', 'Choose Role'), ('Student', 'Student'), ('Faculty/Staff', 'Faculty/Staff')], default='Choose Role', max_length=20)),
                ('password', models.CharField(max_length=128)),
>>>>>>> b32e3409f2d87f193ea8976c0fd0ca6edf64df33
                ('confirm_password', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, related_name='registration_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='registration_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='SubComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.news')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
>>>>>>> b32e3409f2d87f193ea8976c0fd0ca6edf64df33
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(default=django.utils.timezone.now)),
                ('OTP', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='SubComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ljnews', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.ljnews')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.news')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('enrollment_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('role', models.CharField(choices=[('Choose Role', 'Choose Role'), ('Student', 'Student'), ('Faculty/Staff', 'Faculty/Staff')], default='Choose Role', max_length=20)),
                ('profile_image', models.ImageField(upload_to='media/profile/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ljnews',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='LjPost_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
=======
>>>>>>> b32e3409f2d87f193ea8976c0fd0ca6edf64df33
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LJNews_likes', to='ApaniNewz.ljnews')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post_likes', to='ApaniNewz.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('article', 'news', 'user')},
=======
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post_likes', to='ApaniNewz.news')),
            ],
            options={
                'unique_together': {('article', 'user')},
>>>>>>> b32e3409f2d87f193ea8976c0fd0ca6edf64df33
            },
        ),
    ]
