# Generated by Django 5.2 on 2025-05-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('Choose Role', 'Choose Role'), ('Student', 'Student'), ('Faculty/Staff', 'Faculty/Staff')], default='Choose Role', max_length=20, null=True),
        ),
    ]
