# Generated by Django 5.1 on 2025-04-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0002_profile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ljnews',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
