# Generated by Django 5.2 on 2025-05-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
