# Generated by Django 5.1 on 2025-02-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0003_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image',
            new_name='newsimage',
        ),
    ]
