# Generated by Django 5.1 on 2025-04-13 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0003_ljnews_views_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ljnews',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
