# Generated by Django 5.1 on 2025-02-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0004_rename_image_news_newsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='newsimage',
        ),
        migrations.AddField(
            model_name='news',
            name='news_image',
            field=models.ImageField(default=1, upload_to='media/news/'),
            preserve_default=False,
        ),
    ]
