# Generated by Django 5.1 on 2025-04-19 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0004_alter_ljnews_views_alter_news_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='LJNews_likes', to='ApaniNewz.ljnews'),
            preserve_default=False,
        ),
    ]
