# Generated by Django 5.1 on 2025-02-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0005_customuser_delete_customuseradmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
