# Generated by Django 5.1 on 2025-04-19 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0005_likes_news'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ljnews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.ljnews'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcomments',
            name='ljnews',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.ljnews'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('article', 'news', 'user')},
        ),
    ]
