# Generated by Django 5.1 on 2025-02-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0005_remove_news_newsimage_news_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='enrollment_number',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
