# Generated by Django 5.1 on 2025-02-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrollment_number',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
