# Generated by Django 5.1 on 2025-04-19 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0006_comment_ljnews_subcomments_ljnews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ljnews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.ljnews'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.news'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Post_likes', to='ApaniNewz.news'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LJNews_likes', to='ApaniNewz.ljnews'),
        ),
        migrations.AlterField(
            model_name='subcomments',
            name='ljnews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.ljnews'),
        ),
        migrations.AlterField(
            model_name='subcomments',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.news'),
        ),
    ]
