# Generated by Django 5.1 on 2025-02-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0006_registration_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='enrollment_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
