# Generated by Django 5.1 on 2025-04-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0007_alter_comment_ljnews_alter_comment_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ljnews',
            name='visibility',
            field=models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('rejected', 'REJECTED')], default='PENDING', max_length=10),
        ),
    ]
