# Generated by Django 5.1 on 2025-02-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0007_profile_enrollment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Faculty/Staff', 'Faculty/Staff')], default='Student', max_length=20),
        ),
    ]
