# Generated by Django 5.1 on 2025-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0008_registration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('Choose Role', 'Choose Role'), ('Student', 'Student'), ('Faculty/Staff', 'Faculty/Staff')], default='Choose Role', max_length=20),
        ),
    ]
