# Generated by Django 5.1 on 2025-02-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0009_alter_profile_enrollment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Choose Role', 'Choose Role'), ('Student', 'Student'), ('Faculty/Staff', 'Faculty/Staff')], default='Choose Role', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='media/profile/'),
            preserve_default=False,
        ),
    ]
