# Generated by Django 5.1 on 2025-04-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0009_alter_ljnews_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ljnews',
            name='visibility',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=255),
        ),
    ]
