# Generated by Django 5.1 on 2025-02-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
