# Generated by Django 5.1 on 2025-04-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0011_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('gallery_image', models.ImageField(upload_to='media/gallery/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
