# Generated by Django 5.1 on 2025-02-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0011_alter_news_likes_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='is_liked',
        ),
    ]
