# Generated by Django 5.1 on 2025-02-28 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0012_remove_likes_is_liked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
