# Generated by Django 5.1 on 2025-04-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0012_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='sub_title',
        ),
        migrations.AddField(
            model_name='slider',
            name='author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
