# Generated by Django 5.1 on 2025-04-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0013_remove_slider_sub_title_slider_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/slider/'),
        ),
    ]
