# Generated by Django 5.1 on 2025-03-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0014_remove_comment_updated_alter_comment_news_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcomments',
            old_name='post',
            new_name='news',
        ),
    ]
