# Generated by Django 5.1 on 2025-05-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0014_alter_slider_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='approved',
            field=models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('NOT APPROVED', 'NOT APPROVED')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ljnews',
            name='visibility',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=255, null=True),
        ),
    ]
