# Generated by Django 5.1 on 2025-03-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0015_rename_post_subcomments_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcomments',
            name='reply',
            field=models.TextField(),
        ),
    ]
