# Generated by Django 5.1 on 2025-05-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0016_alter_registration_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='profile_image',
            field=models.ImageField(default=1, upload_to='media/profile/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
