# Generated by Django 5.1 on 2025-03-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0016_alter_subcomments_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcomments',
            old_name='comment',
            new_name='parent_comment',
        ),
    ]
