# Generated by Django 5.1 on 2025-03-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0019_ljnews_is_featured_alter_ljnews_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='Is_Featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
