# Generated by Django 5.1 on 2025-03-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0020_news_is_featured_alter_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ljnews',
            old_name='Is_Featured',
            new_name='is_featured',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='Is_Featured',
            new_name='is_featured',
        ),
        migrations.AlterField(
            model_name='ljnews',
            name='ljnews_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/ljnews/'),
        ),
    ]
