# Generated by Django 5.1 on 2025-03-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0021_rename_is_featured_ljnews_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
