# Generated by Django 5.1 on 2025-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0022_registration_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ljnews',
            name='auther_id',
            field=models.EmailField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='auther_id',
            field=models.EmailField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
