# Generated by Django 5.1 on 2025-03-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0023_ljnews_auther_id_news_auther_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ljnews',
            old_name='auther_id',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='auther_id',
            new_name='author_id',
        ),
    ]
