# Generated by Django 5.2 on 2025-05-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0024_alter_profile_user_alter_userotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='ApaniNewz.registration'),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApaniNewz.registration'),
        ),
    ]
