# Generated by Django 5.1 on 2025-03-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApaniNewz', '0024_rename_auther_id_ljnews_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ljnews',
            name='author_id',
            field=models.EmailField(max_length=255),
        ),
    ]
